export const data = [
  {
    id: 'MLB1786478708',
    site_id: 'MLB',
    title: 'Computador Cpu Intel I3 4gb Ssd 120gb Hdmi Pronta Entrega',
    seller: {
      id: 298832663,
      permalink: 'http://perfil.mercadolivre.com.br/GAMING+INFO',
      registration_date: '2018-01-28T11:55:55.000-04:00',
      car_dealer: false,
      real_estate_agency: false,
      tags: [
        'normal',
        'credits_profile',
        'mshops',
        'messages_as_seller',
        'messages_as_buyer',
      ],
      seller_reputation: {
        transactions: {
          total: 9425,
          canceled: 664,
          period: 'historic',
          ratings: {
            negative: 0.05,
            positive: 0.93,
            neutral: 0.02,
          },
          completed: 8761,
        },
        power_seller_status: 'platinum',
        metrics: {
          claims: {
            rate: 0,
            excluded: {
              real_rate: 0.0284,
              real_value: 136,
            },
            value: 0,
            period: '60 days',
          },
          delayed_handling_time: {
            rate: 0,
            excluded: {
              real_rate: 0.0954,
              real_value: 423,
            },
            value: 0,
            period: '60 days',
          },
          sales: {
            period: '60 days',
            completed: 4478,
          },
          cancellations: {
            rate: 0,
            excluded: {
              real_rate: 0,
              real_value: 1,
            },
            value: 0,
            period: '60 days',
          },
        },
        protection_end_date: '2021-05-14T00:00:00.000-04:00',
        real_level: 'green_platinum',
        level_id: '5_green',
      },
    },
    price: 1200,
    prices: {
      id: 'MLB1786478708',
      prices: [
        {
          id: '5',
          type: 'standard',
          conditions: {
            context_restrictions: [
            ],
            start_time: null,
            end_time: null,
            eligible: true,
          },
          amount: 1200,
          regular_amount: null,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          metadata: {
          },
          last_updated: '2021-04-30T11:16:51Z',
        },
      ],
      presentation: {
        display_currency: 'BRL',
      },
      payment_method_prices: [
      ],
      reference_prices: [
      ],
      purchase_discounts: [
      ],
    },
    sale_price: null,
    currency_id: 'BRL',
    available_quantity: 1,
    sold_quantity: 250,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_pro',
    stop_time: '2041-01-29T04:00:00.000Z',
    condition: 'new',
    permalink: 'https://produto.mercadolivre.com.br/MLB-1786478708-computador-cpu-intel-i3-4gb-ssd-120gb-hdmi-pronta-entrega-_JM',
    thumbnail: 'http://http2.mlstatic.com/D_783932-MLB43487722056_092020-I.jpg',
    thumbnail_id: '783932-MLB43487722056_092020',
    accepts_mercadopago: true,
    installments: {
      quantity: 12,
      amount: 100,
      rate: 0,
      currency_id: 'BRL',
    },
    address: {
      state_id: 'BR-SP',
      state_name: 'São Paulo',
      city_id: 'BR-SP-44',
      city_name: 'São Paulo',
    },
    shipping: {
      free_shipping: true,
      mode: 'me2',
      tags: [
        'self_service_in',
        'mandatory_free_shipping',
      ],
      logistic_type: 'cross_docking',
      store_pick_up: false,
    },
    seller_address: {
      id: '',
      comment: '',
      address_line: '',
      zip_code: '',
      country: {
        id: 'BR',
        name: 'Brasil',
      },
      state: {
        id: 'BR-SP',
        name: 'São Paulo',
      },
      city: {
        id: 'BR-SP-44',
        name: 'São Paulo',
      },
      latitude: '',
      longitude: '',
    },
    attributes: [
      {
        id: 'BRAND',
        name: 'Marca',
        value_id: null,
        value_name: 'GAME INFO',
        value_struct: null,
        values: [
          {
            source: 2860837171021627,
            id: null,
            name: 'GAME INFO',
            struct: null,
          },
        ],
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        source: 2860837171021627,
      },
      {
        values: [
          {
            id: '2230284',
            name: 'Novo',
            struct: null,
            source: 2860837171021627,
          },
        ],
        attribute_group_id: 'OTHERS',
        name: 'Condição do item',
        value_id: '2230284',
        value_name: 'Novo',
        source: 2860837171021627,
        id: 'ITEM_CONDITION',
        value_struct: null,
        attribute_group_name: 'Outros',
      },
      {
        name: 'Modelo',
        value_id: null,
        value_name: 'Office',
        value_struct: null,
        attribute_group_name: 'Outros',
        id: 'MODEL',
        values: [
          {
            id: null,
            name: 'Office',
            struct: null,
            source: 2860837171021627,
          },
        ],
        attribute_group_id: 'OTHERS',
        source: 2860837171021627,
      },
    ],
    differential_pricing: {
      id: 33580182,
    },
    original_price: null,
    category_id: 'MLB1649',
    official_store_id: null,
    domain_id: 'MLB-DESKTOP_COMPUTERS',
    catalog_product_id: null,
    tags: [
      'good_quality_picture',
      'good_quality_thumbnail',
      'loyalty_discount_eligible',
      'immediate_payment',
      'cart_eligible',
      'shipping_guaranteed',
    ],
    order_backend: 1,
    use_thumbnail_id: true,
  },
  {
    id: 'MLB1218701240',
    site_id: 'MLB',
    title: 'Computador Pc Completo Intel 8gb Hd 500gb Monitor 18 Wind 10',
    seller: {
      id: 225513622,
      permalink: 'http://perfil.mercadolivre.com.br/AMORIM.SHOP',
      registration_date: '2018-04-06T09:36:49.000-04:00',
      car_dealer: false,
      real_estate_agency: false,
      tags: [
        'normal',
        'mshops',
        'messages_as_seller',
        'messages_as_buyer',
      ],
      seller_reputation: {
        transactions: {
          total: 2548,
          canceled: 260,
          period: 'historic',
          ratings: {
            negative: 0.06,
            positive: 0.9,
            neutral: 0.04,
          },
          completed: 2288,
        },
        power_seller_status: 'gold',
        metrics: {
          claims: {
            rate: 0.025,
            value: 7,
            period: '60 days',
          },
          delayed_handling_time: {
            rate: 0,
            value: 0,
            period: '60 days',
          },
          sales: {
            period: '60 days',
            completed: 253,
          },
          cancellations: {
            rate: 0,
            value: 1,
            period: '60 days',
          },
        },
        level_id: '5_green',
      },
    },
    price: 2279.05,
    prices: {
      id: 'MLB1218701240',
      prices: [
        {
          id: '4',
          type: 'standard',
          conditions: {
            context_restrictions: [
            ],
            start_time: null,
            end_time: null,
            eligible: true,
          },
          amount: 2399,
          regular_amount: null,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          metadata: {
          },
          last_updated: '2021-04-01T01:18:19Z',
        },
        {
          id: '5',
          type: 'promotion',
          conditions: {
            context_restrictions: [
            ],
            start_time: '2021-05-02T03:00:00Z',
            end_time: '2021-05-09T02:59:59Z',
            eligible: true,
          },
          amount: 2279.05,
          regular_amount: 2399,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          metadata: {
            promotion_id: '7609868-MLB1218701240',
            promotion_type: 'custom',
          },
          last_updated: '2021-05-02T14:15:59Z',
        },
      ],
      presentation: {
        display_currency: 'BRL',
      },
      payment_method_prices: [
      ],
      reference_prices: [
      ],
      purchase_discounts: [
      ],
    },
    sale_price: null,
    currency_id: 'BRL',
    available_quantity: 1,
    sold_quantity: 250,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_pro',
    stop_time: '2040-11-11T20:09:13.000Z',
    condition: 'new',
    permalink: 'https://produto.mercadolivre.com.br/MLB-1218701240-computador-pc-completo-intel-8gb-hd-500gb-monitor-18-wind-10-_JM',
    thumbnail: 'http://http2.mlstatic.com/D_817225-MLB45400911410_032021-I.jpg',
    thumbnail_id: '817225-MLB45400911410_032021',
    accepts_mercadopago: true,
    installments: {
      quantity: 12,
      amount: 189.92,
      rate: 0,
      currency_id: 'BRL',
    },
    address: {
      state_id: 'BR-SP',
      state_name: 'São Paulo',
      city_id: 'BR-SP-44',
      city_name: 'São Paulo',
    },
    shipping: {
      free_shipping: true,
      mode: 'me2',
      tags: [
        'fulfillment',
        'self_service_in',
        'mandatory_free_shipping',
      ],
      logistic_type: 'fulfillment',
      store_pick_up: false,
    },
    seller_address: {
      id: '',
      comment: '',
      address_line: '',
      zip_code: '',
      country: {
        id: 'BR',
        name: 'Brasil',
      },
      state: {
        id: 'BR-SP',
        name: 'São Paulo',
      },
      city: {
        id: 'BR-SP-44',
        name: 'São Paulo',
      },
      latitude: '',
      longitude: '',
    },
    attributes: [
      {
        value_name: 'Intel',
        values: [
          {
            id: '7855833',
            name: 'Intel',
            struct: null,
            source: 9903,
          },
        ],
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        id: 'BRAND',
        name: 'Marca',
        value_id: '7855833',
        value_struct: null,
        source: 9903,
      },
      {
        value_id: '2230284',
        values: [
          {
            id: '2230284',
            name: 'Novo',
            struct: null,
            source: 1,
          },
        ],
        attribute_group_id: 'OTHERS',
        id: 'ITEM_CONDITION',
        name: 'Condição do item',
        value_name: 'Novo',
        value_struct: null,
        attribute_group_name: 'Outros',
        source: 1,
      },
      {
        name: 'Modelo',
        value_id: null,
        value_struct: null,
        attribute_group_name: 'Outros',
        id: 'MODEL',
        value_name: 'i3',
        values: [
          {
            id: null,
            name: 'i3',
            struct: null,
            source: 9903,
          },
        ],
        attribute_group_id: 'OTHERS',
        source: 9903,
      },
      {
        id: 'PACKAGE_LENGTH',
        value_name: '52.5 cm',
        value_struct: {
          number: 52.5,
          unit: 'cm',
        },
        attribute_group_name: 'Outros',
        source: 4333789534002961,
        name: 'Comprimento da embalagem',
        value_id: null,
        values: [
          {
            id: null,
            name: '52.5 cm',
            struct: {
              number: 52.5,
              unit: 'cm',
            },
            source: 4333789534002961,
          },
        ],
        attribute_group_id: 'OTHERS',
      },
      {
        attribute_group_id: 'OTHERS',
        source: 4333789534002961,
        value_id: null,
        value_struct: {
          number: 9530,
          unit: 'g',
        },
        values: [
          {
            name: '9530 g',
            struct: {
              number: 9530,
              unit: 'g',
            },
            source: 4333789534002961,
            id: null,
          },
        ],
        attribute_group_name: 'Outros',
        id: 'PACKAGE_WEIGHT',
        name: 'Peso da embalagem',
        value_name: '9530 g',
      },
    ],
    differential_pricing: {
      id: 33580182,
    },
    original_price: 2399,
    category_id: 'MLB1649',
    official_store_id: null,
    domain_id: 'MLB-DESKTOP_COMPUTERS',
    catalog_product_id: null,
    tags: [
      'good_quality_picture',
      'good_quality_thumbnail',
      'loyalty_discount_eligible',
      'immediate_payment',
      'cart_eligible',
      'shipping_guaranteed',
    ],
    order_backend: 2,
    use_thumbnail_id: true,
  },
  {
    id: 'MLB1786478708',
    site_id: 'MLB',
    title: 'Computador Cpu Intel I3 4gb Ssd 120gb Hdmi Pronta Entrega',
    seller: {
      id: 298832663,
      permalink: 'http://perfil.mercadolivre.com.br/GAMING+INFO',
      registration_date: '2018-01-28T11:55:55.000-04:00',
      car_dealer: false,
      real_estate_agency: false,
      tags: [
        'normal',
        'credits_profile',
        'mshops',
        'messages_as_seller',
        'messages_as_buyer',
      ],
      seller_reputation: {
        transactions: {
          total: 9425,
          canceled: 664,
          period: 'historic',
          ratings: {
            negative: 0.05,
            positive: 0.93,
            neutral: 0.02,
          },
          completed: 8761,
        },
        power_seller_status: 'platinum',
        metrics: {
          claims: {
            rate: 0,
            excluded: {
              real_rate: 0.0284,
              real_value: 136,
            },
            value: 0,
            period: '60 days',
          },
          delayed_handling_time: {
            rate: 0,
            excluded: {
              real_rate: 0.0954,
              real_value: 423,
            },
            value: 0,
            period: '60 days',
          },
          sales: {
            period: '60 days',
            completed: 4478,
          },
          cancellations: {
            rate: 0,
            excluded: {
              real_rate: 0,
              real_value: 1,
            },
            value: 0,
            period: '60 days',
          },
        },
        protection_end_date: '2021-05-14T00:00:00.000-04:00',
        real_level: 'green_platinum',
        level_id: '5_green',
      },
    },
    price: 1200,
    prices: {
      id: 'MLB1786478708',
      prices: [
        {
          id: '5',
          type: 'standard',
          conditions: {
            context_restrictions: [
            ],
            start_time: null,
            end_time: null,
            eligible: true,
          },
          amount: 1200,
          regular_amount: null,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          metadata: {
          },
          last_updated: '2021-04-30T11:16:51Z',
        },
      ],
      presentation: {
        display_currency: 'BRL',
      },
      payment_method_prices: [
      ],
      reference_prices: [
      ],
      purchase_discounts: [
      ],
    },
    sale_price: null,
    currency_id: 'BRL',
    available_quantity: 1,
    sold_quantity: 250,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_pro',
    stop_time: '2041-01-29T04:00:00.000Z',
    condition: 'new',
    permalink: 'https://produto.mercadolivre.com.br/MLB-1786478708-computador-cpu-intel-i3-4gb-ssd-120gb-hdmi-pronta-entrega-_JM',
    thumbnail: 'http://http2.mlstatic.com/D_783932-MLB43487722056_092020-I.jpg',
    thumbnail_id: '783932-MLB43487722056_092020',
    accepts_mercadopago: true,
    installments: {
      quantity: 12,
      amount: 100,
      rate: 0,
      currency_id: 'BRL',
    },
    address: {
      state_id: 'BR-SP',
      state_name: 'São Paulo',
      city_id: 'BR-SP-44',
      city_name: 'São Paulo',
    },
    shipping: {
      free_shipping: true,
      mode: 'me2',
      tags: [
        'self_service_in',
        'mandatory_free_shipping',
      ],
      logistic_type: 'cross_docking',
      store_pick_up: false,
    },
    seller_address: {
      id: '',
      comment: '',
      address_line: '',
      zip_code: '',
      country: {
        id: 'BR',
        name: 'Brasil',
      },
      state: {
        id: 'BR-SP',
        name: 'São Paulo',
      },
      city: {
        id: 'BR-SP-44',
        name: 'São Paulo',
      },
      latitude: '',
      longitude: '',
    },
    attributes: [
      {
        id: 'BRAND',
        name: 'Marca',
        value_id: null,
        value_name: 'GAME INFO',
        value_struct: null,
        values: [
          {
            source: 2860837171021627,
            id: null,
            name: 'GAME INFO',
            struct: null,
          },
        ],
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        source: 2860837171021627,
      },
      {
        values: [
          {
            id: '2230284',
            name: 'Novo',
            struct: null,
            source: 2860837171021627,
          },
        ],
        attribute_group_id: 'OTHERS',
        name: 'Condição do item',
        value_id: '2230284',
        value_name: 'Novo',
        source: 2860837171021627,
        id: 'ITEM_CONDITION',
        value_struct: null,
        attribute_group_name: 'Outros',
      },
      {
        name: 'Modelo',
        value_id: null,
        value_name: 'Office',
        value_struct: null,
        attribute_group_name: 'Outros',
        id: 'MODEL',
        values: [
          {
            id: null,
            name: 'Office',
            struct: null,
            source: 2860837171021627,
          },
        ],
        attribute_group_id: 'OTHERS',
        source: 2860837171021627,
      },
    ],
    differential_pricing: {
      id: 33580182,
    },
    original_price: null,
    category_id: 'MLB1649',
    official_store_id: null,
    domain_id: 'MLB-DESKTOP_COMPUTERS',
    catalog_product_id: null,
    tags: [
      'good_quality_picture',
      'good_quality_thumbnail',
      'loyalty_discount_eligible',
      'immediate_payment',
      'cart_eligible',
      'shipping_guaranteed',
    ],
    order_backend: 1,
    use_thumbnail_id: true,
  },
  {
    id: 'MLB1218701240',
    site_id: 'MLB',
    title: 'Computador Pc Completo Intel 8gb Hd 500gb Monitor 18 Wind 10',
    seller: {
      id: 225513622,
      permalink: 'http://perfil.mercadolivre.com.br/AMORIM.SHOP',
      registration_date: '2018-04-06T09:36:49.000-04:00',
      car_dealer: false,
      real_estate_agency: false,
      tags: [
        'normal',
        'mshops',
        'messages_as_seller',
        'messages_as_buyer',
      ],
      seller_reputation: {
        transactions: {
          total: 2548,
          canceled: 260,
          period: 'historic',
          ratings: {
            negative: 0.06,
            positive: 0.9,
            neutral: 0.04,
          },
          completed: 2288,
        },
        power_seller_status: 'gold',
        metrics: {
          claims: {
            rate: 0.025,
            value: 7,
            period: '60 days',
          },
          delayed_handling_time: {
            rate: 0,
            value: 0,
            period: '60 days',
          },
          sales: {
            period: '60 days',
            completed: 253,
          },
          cancellations: {
            rate: 0,
            value: 1,
            period: '60 days',
          },
        },
        level_id: '5_green',
      },
    },
    price: 2279.05,
    prices: {
      id: 'MLB1218701240',
      prices: [
        {
          id: '4',
          type: 'standard',
          conditions: {
            context_restrictions: [
            ],
            start_time: null,
            end_time: null,
            eligible: true,
          },
          amount: 2399,
          regular_amount: null,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          metadata: {
          },
          last_updated: '2021-04-01T01:18:19Z',
        },
        {
          id: '5',
          type: 'promotion',
          conditions: {
            context_restrictions: [
            ],
            start_time: '2021-05-02T03:00:00Z',
            end_time: '2021-05-09T02:59:59Z',
            eligible: true,
          },
          amount: 2279.05,
          regular_amount: 2399,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          metadata: {
            promotion_id: '7609868-MLB1218701240',
            promotion_type: 'custom',
          },
          last_updated: '2021-05-02T14:15:59Z',
        },
      ],
      presentation: {
        display_currency: 'BRL',
      },
      payment_method_prices: [
      ],
      reference_prices: [
      ],
      purchase_discounts: [
      ],
    },
    sale_price: null,
    currency_id: 'BRL',
    available_quantity: 1,
    sold_quantity: 250,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_pro',
    stop_time: '2040-11-11T20:09:13.000Z',
    condition: 'new',
    permalink: 'https://produto.mercadolivre.com.br/MLB-1218701240-computador-pc-completo-intel-8gb-hd-500gb-monitor-18-wind-10-_JM',
    thumbnail: 'http://http2.mlstatic.com/D_817225-MLB45400911410_032021-I.jpg',
    thumbnail_id: '817225-MLB45400911410_032021',
    accepts_mercadopago: true,
    installments: {
      quantity: 12,
      amount: 189.92,
      rate: 0,
      currency_id: 'BRL',
    },
    address: {
      state_id: 'BR-SP',
      state_name: 'São Paulo',
      city_id: 'BR-SP-44',
      city_name: 'São Paulo',
    },
    shipping: {
      free_shipping: true,
      mode: 'me2',
      tags: [
        'fulfillment',
        'self_service_in',
        'mandatory_free_shipping',
      ],
      logistic_type: 'fulfillment',
      store_pick_up: false,
    },
    seller_address: {
      id: '',
      comment: '',
      address_line: '',
      zip_code: '',
      country: {
        id: 'BR',
        name: 'Brasil',
      },
      state: {
        id: 'BR-SP',
        name: 'São Paulo',
      },
      city: {
        id: 'BR-SP-44',
        name: 'São Paulo',
      },
      latitude: '',
      longitude: '',
    },
    attributes: [
      {
        value_name: 'Intel',
        values: [
          {
            id: '7855833',
            name: 'Intel',
            struct: null,
            source: 9903,
          },
        ],
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        id: 'BRAND',
        name: 'Marca',
        value_id: '7855833',
        value_struct: null,
        source: 9903,
      },
      {
        value_id: '2230284',
        values: [
          {
            id: '2230284',
            name: 'Novo',
            struct: null,
            source: 1,
          },
        ],
        attribute_group_id: 'OTHERS',
        id: 'ITEM_CONDITION',
        name: 'Condição do item',
        value_name: 'Novo',
        value_struct: null,
        attribute_group_name: 'Outros',
        source: 1,
      },
      {
        name: 'Modelo',
        value_id: null,
        value_struct: null,
        attribute_group_name: 'Outros',
        id: 'MODEL',
        value_name: 'i3',
        values: [
          {
            id: null,
            name: 'i3',
            struct: null,
            source: 9903,
          },
        ],
        attribute_group_id: 'OTHERS',
        source: 9903,
      },
      {
        id: 'PACKAGE_LENGTH',
        value_name: '52.5 cm',
        value_struct: {
          number: 52.5,
          unit: 'cm',
        },
        attribute_group_name: 'Outros',
        source: 4333789534002961,
        name: 'Comprimento da embalagem',
        value_id: null,
        values: [
          {
            id: null,
            name: '52.5 cm',
            struct: {
              number: 52.5,
              unit: 'cm',
            },
            source: 4333789534002961,
          },
        ],
        attribute_group_id: 'OTHERS',
      },
      {
        attribute_group_id: 'OTHERS',
        source: 4333789534002961,
        value_id: null,
        value_struct: {
          number: 9530,
          unit: 'g',
        },
        values: [
          {
            name: '9530 g',
            struct: {
              number: 9530,
              unit: 'g',
            },
            source: 4333789534002961,
            id: null,
          },
        ],
        attribute_group_name: 'Outros',
        id: 'PACKAGE_WEIGHT',
        name: 'Peso da embalagem',
        value_name: '9530 g',
      },
    ],
    differential_pricing: {
      id: 33580182,
    },
    original_price: 2399,
    category_id: 'MLB1649',
    official_store_id: null,
    domain_id: 'MLB-DESKTOP_COMPUTERS',
    catalog_product_id: null,
    tags: [
      'good_quality_picture',
      'good_quality_thumbnail',
      'loyalty_discount_eligible',
      'immediate_payment',
      'cart_eligible',
      'shipping_guaranteed',
    ],
    order_backend: 2,
    use_thumbnail_id: true,
  },
  {
    id: 'MLB1786478708',
    site_id: 'MLB',
    title: 'Computador Cpu Intel I3 4gb Ssd 120gb Hdmi Pronta Entrega',
    seller: {
      id: 298832663,
      permalink: 'http://perfil.mercadolivre.com.br/GAMING+INFO',
      registration_date: '2018-01-28T11:55:55.000-04:00',
      car_dealer: false,
      real_estate_agency: false,
      tags: [
        'normal',
        'credits_profile',
        'mshops',
        'messages_as_seller',
        'messages_as_buyer',
      ],
      seller_reputation: {
        transactions: {
          total: 9425,
          canceled: 664,
          period: 'historic',
          ratings: {
            negative: 0.05,
            positive: 0.93,
            neutral: 0.02,
          },
          completed: 8761,
        },
        power_seller_status: 'platinum',
        metrics: {
          claims: {
            rate: 0,
            excluded: {
              real_rate: 0.0284,
              real_value: 136,
            },
            value: 0,
            period: '60 days',
          },
          delayed_handling_time: {
            rate: 0,
            excluded: {
              real_rate: 0.0954,
              real_value: 423,
            },
            value: 0,
            period: '60 days',
          },
          sales: {
            period: '60 days',
            completed: 4478,
          },
          cancellations: {
            rate: 0,
            excluded: {
              real_rate: 0,
              real_value: 1,
            },
            value: 0,
            period: '60 days',
          },
        },
        protection_end_date: '2021-05-14T00:00:00.000-04:00',
        real_level: 'green_platinum',
        level_id: '5_green',
      },
    },
    price: 1200,
    prices: {
      id: 'MLB1786478708',
      prices: [
        {
          id: '5',
          type: 'standard',
          conditions: {
            context_restrictions: [
            ],
            start_time: null,
            end_time: null,
            eligible: true,
          },
          amount: 1200,
          regular_amount: null,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          metadata: {
          },
          last_updated: '2021-04-30T11:16:51Z',
        },
      ],
      presentation: {
        display_currency: 'BRL',
      },
      payment_method_prices: [
      ],
      reference_prices: [
      ],
      purchase_discounts: [
      ],
    },
    sale_price: null,
    currency_id: 'BRL',
    available_quantity: 1,
    sold_quantity: 250,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_pro',
    stop_time: '2041-01-29T04:00:00.000Z',
    condition: 'new',
    permalink: 'https://produto.mercadolivre.com.br/MLB-1786478708-computador-cpu-intel-i3-4gb-ssd-120gb-hdmi-pronta-entrega-_JM',
    thumbnail: 'http://http2.mlstatic.com/D_783932-MLB43487722056_092020-I.jpg',
    thumbnail_id: '783932-MLB43487722056_092020',
    accepts_mercadopago: true,
    installments: {
      quantity: 12,
      amount: 100,
      rate: 0,
      currency_id: 'BRL',
    },
    address: {
      state_id: 'BR-SP',
      state_name: 'São Paulo',
      city_id: 'BR-SP-44',
      city_name: 'São Paulo',
    },
    shipping: {
      free_shipping: true,
      mode: 'me2',
      tags: [
        'self_service_in',
        'mandatory_free_shipping',
      ],
      logistic_type: 'cross_docking',
      store_pick_up: false,
    },
    seller_address: {
      id: '',
      comment: '',
      address_line: '',
      zip_code: '',
      country: {
        id: 'BR',
        name: 'Brasil',
      },
      state: {
        id: 'BR-SP',
        name: 'São Paulo',
      },
      city: {
        id: 'BR-SP-44',
        name: 'São Paulo',
      },
      latitude: '',
      longitude: '',
    },
    attributes: [
      {
        id: 'BRAND',
        name: 'Marca',
        value_id: null,
        value_name: 'GAME INFO',
        value_struct: null,
        values: [
          {
            source: 2860837171021627,
            id: null,
            name: 'GAME INFO',
            struct: null,
          },
        ],
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        source: 2860837171021627,
      },
      {
        values: [
          {
            id: '2230284',
            name: 'Novo',
            struct: null,
            source: 2860837171021627,
          },
        ],
        attribute_group_id: 'OTHERS',
        name: 'Condição do item',
        value_id: '2230284',
        value_name: 'Novo',
        source: 2860837171021627,
        id: 'ITEM_CONDITION',
        value_struct: null,
        attribute_group_name: 'Outros',
      },
      {
        name: 'Modelo',
        value_id: null,
        value_name: 'Office',
        value_struct: null,
        attribute_group_name: 'Outros',
        id: 'MODEL',
        values: [
          {
            id: null,
            name: 'Office',
            struct: null,
            source: 2860837171021627,
          },
        ],
        attribute_group_id: 'OTHERS',
        source: 2860837171021627,
      },
    ],
    differential_pricing: {
      id: 33580182,
    },
    original_price: null,
    category_id: 'MLB1649',
    official_store_id: null,
    domain_id: 'MLB-DESKTOP_COMPUTERS',
    catalog_product_id: null,
    tags: [
      'good_quality_picture',
      'good_quality_thumbnail',
      'loyalty_discount_eligible',
      'immediate_payment',
      'cart_eligible',
      'shipping_guaranteed',
    ],
    order_backend: 1,
    use_thumbnail_id: true,
  },
  {
    id: 'MLB1218701240',
    site_id: 'MLB',
    title: 'Computador Pc Completo Intel 8gb Hd 500gb Monitor 18 Wind 10',
    seller: {
      id: 225513622,
      permalink: 'http://perfil.mercadolivre.com.br/AMORIM.SHOP',
      registration_date: '2018-04-06T09:36:49.000-04:00',
      car_dealer: false,
      real_estate_agency: false,
      tags: [
        'normal',
        'mshops',
        'messages_as_seller',
        'messages_as_buyer',
      ],
      seller_reputation: {
        transactions: {
          total: 2548,
          canceled: 260,
          period: 'historic',
          ratings: {
            negative: 0.06,
            positive: 0.9,
            neutral: 0.04,
          },
          completed: 2288,
        },
        power_seller_status: 'gold',
        metrics: {
          claims: {
            rate: 0.025,
            value: 7,
            period: '60 days',
          },
          delayed_handling_time: {
            rate: 0,
            value: 0,
            period: '60 days',
          },
          sales: {
            period: '60 days',
            completed: 253,
          },
          cancellations: {
            rate: 0,
            value: 1,
            period: '60 days',
          },
        },
        level_id: '5_green',
      },
    },
    price: 2279.05,
    prices: {
      id: 'MLB1218701240',
      prices: [
        {
          id: '4',
          type: 'standard',
          conditions: {
            context_restrictions: [
            ],
            start_time: null,
            end_time: null,
            eligible: true,
          },
          amount: 2399,
          regular_amount: null,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          metadata: {
          },
          last_updated: '2021-04-01T01:18:19Z',
        },
        {
          id: '5',
          type: 'promotion',
          conditions: {
            context_restrictions: [
            ],
            start_time: '2021-05-02T03:00:00Z',
            end_time: '2021-05-09T02:59:59Z',
            eligible: true,
          },
          amount: 2279.05,
          regular_amount: 2399,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          metadata: {
            promotion_id: '7609868-MLB1218701240',
            promotion_type: 'custom',
          },
          last_updated: '2021-05-02T14:15:59Z',
        },
      ],
      presentation: {
        display_currency: 'BRL',
      },
      payment_method_prices: [
      ],
      reference_prices: [
      ],
      purchase_discounts: [
      ],
    },
    sale_price: null,
    currency_id: 'BRL',
    available_quantity: 1,
    sold_quantity: 250,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_pro',
    stop_time: '2040-11-11T20:09:13.000Z',
    condition: 'new',
    permalink: 'https://produto.mercadolivre.com.br/MLB-1218701240-computador-pc-completo-intel-8gb-hd-500gb-monitor-18-wind-10-_JM',
    thumbnail: 'http://http2.mlstatic.com/D_817225-MLB45400911410_032021-I.jpg',
    thumbnail_id: '817225-MLB45400911410_032021',
    accepts_mercadopago: true,
    installments: {
      quantity: 12,
      amount: 189.92,
      rate: 0,
      currency_id: 'BRL',
    },
    address: {
      state_id: 'BR-SP',
      state_name: 'São Paulo',
      city_id: 'BR-SP-44',
      city_name: 'São Paulo',
    },
    shipping: {
      free_shipping: true,
      mode: 'me2',
      tags: [
        'fulfillment',
        'self_service_in',
        'mandatory_free_shipping',
      ],
      logistic_type: 'fulfillment',
      store_pick_up: false,
    },
    seller_address: {
      id: '',
      comment: '',
      address_line: '',
      zip_code: '',
      country: {
        id: 'BR',
        name: 'Brasil',
      },
      state: {
        id: 'BR-SP',
        name: 'São Paulo',
      },
      city: {
        id: 'BR-SP-44',
        name: 'São Paulo',
      },
      latitude: '',
      longitude: '',
    },
    attributes: [
      {
        value_name: 'Intel',
        values: [
          {
            id: '7855833',
            name: 'Intel',
            struct: null,
            source: 9903,
          },
        ],
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        id: 'BRAND',
        name: 'Marca',
        value_id: '7855833',
        value_struct: null,
        source: 9903,
      },
      {
        value_id: '2230284',
        values: [
          {
            id: '2230284',
            name: 'Novo',
            struct: null,
            source: 1,
          },
        ],
        attribute_group_id: 'OTHERS',
        id: 'ITEM_CONDITION',
        name: 'Condição do item',
        value_name: 'Novo',
        value_struct: null,
        attribute_group_name: 'Outros',
        source: 1,
      },
      {
        name: 'Modelo',
        value_id: null,
        value_struct: null,
        attribute_group_name: 'Outros',
        id: 'MODEL',
        value_name: 'i3',
        values: [
          {
            id: null,
            name: 'i3',
            struct: null,
            source: 9903,
          },
        ],
        attribute_group_id: 'OTHERS',
        source: 9903,
      },
      {
        id: 'PACKAGE_LENGTH',
        value_name: '52.5 cm',
        value_struct: {
          number: 52.5,
          unit: 'cm',
        },
        attribute_group_name: 'Outros',
        source: 4333789534002961,
        name: 'Comprimento da embalagem',
        value_id: null,
        values: [
          {
            id: null,
            name: '52.5 cm',
            struct: {
              number: 52.5,
              unit: 'cm',
            },
            source: 4333789534002961,
          },
        ],
        attribute_group_id: 'OTHERS',
      },
      {
        attribute_group_id: 'OTHERS',
        source: 4333789534002961,
        value_id: null,
        value_struct: {
          number: 9530,
          unit: 'g',
        },
        values: [
          {
            name: '9530 g',
            struct: {
              number: 9530,
              unit: 'g',
            },
            source: 4333789534002961,
            id: null,
          },
        ],
        attribute_group_name: 'Outros',
        id: 'PACKAGE_WEIGHT',
        name: 'Peso da embalagem',
        value_name: '9530 g',
      },
    ],
    differential_pricing: {
      id: 33580182,
    },
    original_price: 2399,
    category_id: 'MLB1649',
    official_store_id: null,
    domain_id: 'MLB-DESKTOP_COMPUTERS',
    catalog_product_id: null,
    tags: [
      'good_quality_picture',
      'good_quality_thumbnail',
      'loyalty_discount_eligible',
      'immediate_payment',
      'cart_eligible',
      'shipping_guaranteed',
    ],
    order_backend: 2,
    use_thumbnail_id: true,
  },
  {
    id: 'MLB1786478708',
    site_id: 'MLB',
    title: 'Computador Cpu Intel I3 4gb Ssd 120gb Hdmi Pronta Entrega',
    seller: {
      id: 298832663,
      permalink: 'http://perfil.mercadolivre.com.br/GAMING+INFO',
      registration_date: '2018-01-28T11:55:55.000-04:00',
      car_dealer: false,
      real_estate_agency: false,
      tags: [
        'normal',
        'credits_profile',
        'mshops',
        'messages_as_seller',
        'messages_as_buyer',
      ],
      seller_reputation: {
        transactions: {
          total: 9425,
          canceled: 664,
          period: 'historic',
          ratings: {
            negative: 0.05,
            positive: 0.93,
            neutral: 0.02,
          },
          completed: 8761,
        },
        power_seller_status: 'platinum',
        metrics: {
          claims: {
            rate: 0,
            excluded: {
              real_rate: 0.0284,
              real_value: 136,
            },
            value: 0,
            period: '60 days',
          },
          delayed_handling_time: {
            rate: 0,
            excluded: {
              real_rate: 0.0954,
              real_value: 423,
            },
            value: 0,
            period: '60 days',
          },
          sales: {
            period: '60 days',
            completed: 4478,
          },
          cancellations: {
            rate: 0,
            excluded: {
              real_rate: 0,
              real_value: 1,
            },
            value: 0,
            period: '60 days',
          },
        },
        protection_end_date: '2021-05-14T00:00:00.000-04:00',
        real_level: 'green_platinum',
        level_id: '5_green',
      },
    },
    price: 1200,
    prices: {
      id: 'MLB1786478708',
      prices: [
        {
          id: '5',
          type: 'standard',
          conditions: {
            context_restrictions: [
            ],
            start_time: null,
            end_time: null,
            eligible: true,
          },
          amount: 1200,
          regular_amount: null,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          metadata: {
          },
          last_updated: '2021-04-30T11:16:51Z',
        },
      ],
      presentation: {
        display_currency: 'BRL',
      },
      payment_method_prices: [
      ],
      reference_prices: [
      ],
      purchase_discounts: [
      ],
    },
    sale_price: null,
    currency_id: 'BRL',
    available_quantity: 1,
    sold_quantity: 250,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_pro',
    stop_time: '2041-01-29T04:00:00.000Z',
    condition: 'new',
    permalink: 'https://produto.mercadolivre.com.br/MLB-1786478708-computador-cpu-intel-i3-4gb-ssd-120gb-hdmi-pronta-entrega-_JM',
    thumbnail: 'http://http2.mlstatic.com/D_783932-MLB43487722056_092020-I.jpg',
    thumbnail_id: '783932-MLB43487722056_092020',
    accepts_mercadopago: true,
    installments: {
      quantity: 12,
      amount: 100,
      rate: 0,
      currency_id: 'BRL',
    },
    address: {
      state_id: 'BR-SP',
      state_name: 'São Paulo',
      city_id: 'BR-SP-44',
      city_name: 'São Paulo',
    },
    shipping: {
      free_shipping: true,
      mode: 'me2',
      tags: [
        'self_service_in',
        'mandatory_free_shipping',
      ],
      logistic_type: 'cross_docking',
      store_pick_up: false,
    },
    seller_address: {
      id: '',
      comment: '',
      address_line: '',
      zip_code: '',
      country: {
        id: 'BR',
        name: 'Brasil',
      },
      state: {
        id: 'BR-SP',
        name: 'São Paulo',
      },
      city: {
        id: 'BR-SP-44',
        name: 'São Paulo',
      },
      latitude: '',
      longitude: '',
    },
    attributes: [
      {
        id: 'BRAND',
        name: 'Marca',
        value_id: null,
        value_name: 'GAME INFO',
        value_struct: null,
        values: [
          {
            source: 2860837171021627,
            id: null,
            name: 'GAME INFO',
            struct: null,
          },
        ],
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        source: 2860837171021627,
      },
      {
        values: [
          {
            id: '2230284',
            name: 'Novo',
            struct: null,
            source: 2860837171021627,
          },
        ],
        attribute_group_id: 'OTHERS',
        name: 'Condição do item',
        value_id: '2230284',
        value_name: 'Novo',
        source: 2860837171021627,
        id: 'ITEM_CONDITION',
        value_struct: null,
        attribute_group_name: 'Outros',
      },
      {
        name: 'Modelo',
        value_id: null,
        value_name: 'Office',
        value_struct: null,
        attribute_group_name: 'Outros',
        id: 'MODEL',
        values: [
          {
            id: null,
            name: 'Office',
            struct: null,
            source: 2860837171021627,
          },
        ],
        attribute_group_id: 'OTHERS',
        source: 2860837171021627,
      },
    ],
    differential_pricing: {
      id: 33580182,
    },
    original_price: null,
    category_id: 'MLB1649',
    official_store_id: null,
    domain_id: 'MLB-DESKTOP_COMPUTERS',
    catalog_product_id: null,
    tags: [
      'good_quality_picture',
      'good_quality_thumbnail',
      'loyalty_discount_eligible',
      'immediate_payment',
      'cart_eligible',
      'shipping_guaranteed',
    ],
    order_backend: 1,
    use_thumbnail_id: true,
  },
  {
    id: 'MLB1218701240',
    site_id: 'MLB',
    title: 'Computador Pc Completo Intel 8gb Hd 500gb Monitor 18 Wind 10',
    seller: {
      id: 225513622,
      permalink: 'http://perfil.mercadolivre.com.br/AMORIM.SHOP',
      registration_date: '2018-04-06T09:36:49.000-04:00',
      car_dealer: false,
      real_estate_agency: false,
      tags: [
        'normal',
        'mshops',
        'messages_as_seller',
        'messages_as_buyer',
      ],
      seller_reputation: {
        transactions: {
          total: 2548,
          canceled: 260,
          period: 'historic',
          ratings: {
            negative: 0.06,
            positive: 0.9,
            neutral: 0.04,
          },
          completed: 2288,
        },
        power_seller_status: 'gold',
        metrics: {
          claims: {
            rate: 0.025,
            value: 7,
            period: '60 days',
          },
          delayed_handling_time: {
            rate: 0,
            value: 0,
            period: '60 days',
          },
          sales: {
            period: '60 days',
            completed: 253,
          },
          cancellations: {
            rate: 0,
            value: 1,
            period: '60 days',
          },
        },
        level_id: '5_green',
      },
    },
    price: 2279.05,
    prices: {
      id: 'MLB1218701240',
      prices: [
        {
          id: '4',
          type: 'standard',
          conditions: {
            context_restrictions: [
            ],
            start_time: null,
            end_time: null,
            eligible: true,
          },
          amount: 2399,
          regular_amount: null,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          metadata: {
          },
          last_updated: '2021-04-01T01:18:19Z',
        },
        {
          id: '5',
          type: 'promotion',
          conditions: {
            context_restrictions: [
            ],
            start_time: '2021-05-02T03:00:00Z',
            end_time: '2021-05-09T02:59:59Z',
            eligible: true,
          },
          amount: 2279.05,
          regular_amount: 2399,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          metadata: {
            promotion_id: '7609868-MLB1218701240',
            promotion_type: 'custom',
          },
          last_updated: '2021-05-02T14:15:59Z',
        },
      ],
      presentation: {
        display_currency: 'BRL',
      },
      payment_method_prices: [
      ],
      reference_prices: [
      ],
      purchase_discounts: [
      ],
    },
    sale_price: null,
    currency_id: 'BRL',
    available_quantity: 1,
    sold_quantity: 250,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_pro',
    stop_time: '2040-11-11T20:09:13.000Z',
    condition: 'new',
    permalink: 'https://produto.mercadolivre.com.br/MLB-1218701240-computador-pc-completo-intel-8gb-hd-500gb-monitor-18-wind-10-_JM',
    thumbnail: 'http://http2.mlstatic.com/D_817225-MLB45400911410_032021-I.jpg',
    thumbnail_id: '817225-MLB45400911410_032021',
    accepts_mercadopago: true,
    installments: {
      quantity: 12,
      amount: 189.92,
      rate: 0,
      currency_id: 'BRL',
    },
    address: {
      state_id: 'BR-SP',
      state_name: 'São Paulo',
      city_id: 'BR-SP-44',
      city_name: 'São Paulo',
    },
    shipping: {
      free_shipping: true,
      mode: 'me2',
      tags: [
        'fulfillment',
        'self_service_in',
        'mandatory_free_shipping',
      ],
      logistic_type: 'fulfillment',
      store_pick_up: false,
    },
    seller_address: {
      id: '',
      comment: '',
      address_line: '',
      zip_code: '',
      country: {
        id: 'BR',
        name: 'Brasil',
      },
      state: {
        id: 'BR-SP',
        name: 'São Paulo',
      },
      city: {
        id: 'BR-SP-44',
        name: 'São Paulo',
      },
      latitude: '',
      longitude: '',
    },
    attributes: [
      {
        value_name: 'Intel',
        values: [
          {
            id: '7855833',
            name: 'Intel',
            struct: null,
            source: 9903,
          },
        ],
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        id: 'BRAND',
        name: 'Marca',
        value_id: '7855833',
        value_struct: null,
        source: 9903,
      },
      {
        value_id: '2230284',
        values: [
          {
            id: '2230284',
            name: 'Novo',
            struct: null,
            source: 1,
          },
        ],
        attribute_group_id: 'OTHERS',
        id: 'ITEM_CONDITION',
        name: 'Condição do item',
        value_name: 'Novo',
        value_struct: null,
        attribute_group_name: 'Outros',
        source: 1,
      },
      {
        name: 'Modelo',
        value_id: null,
        value_struct: null,
        attribute_group_name: 'Outros',
        id: 'MODEL',
        value_name: 'i3',
        values: [
          {
            id: null,
            name: 'i3',
            struct: null,
            source: 9903,
          },
        ],
        attribute_group_id: 'OTHERS',
        source: 9903,
      },
      {
        id: 'PACKAGE_LENGTH',
        value_name: '52.5 cm',
        value_struct: {
          number: 52.5,
          unit: 'cm',
        },
        attribute_group_name: 'Outros',
        source: 4333789534002961,
        name: 'Comprimento da embalagem',
        value_id: null,
        values: [
          {
            id: null,
            name: '52.5 cm',
            struct: {
              number: 52.5,
              unit: 'cm',
            },
            source: 4333789534002961,
          },
        ],
        attribute_group_id: 'OTHERS',
      },
      {
        attribute_group_id: 'OTHERS',
        source: 4333789534002961,
        value_id: null,
        value_struct: {
          number: 9530,
          unit: 'g',
        },
        values: [
          {
            name: '9530 g',
            struct: {
              number: 9530,
              unit: 'g',
            },
            source: 4333789534002961,
            id: null,
          },
        ],
        attribute_group_name: 'Outros',
        id: 'PACKAGE_WEIGHT',
        name: 'Peso da embalagem',
        value_name: '9530 g',
      },
    ],
    differential_pricing: {
      id: 33580182,
    },
    original_price: 2399,
    category_id: 'MLB1649',
    official_store_id: null,
    domain_id: 'MLB-DESKTOP_COMPUTERS',
    catalog_product_id: null,
    tags: [
      'good_quality_picture',
      'good_quality_thumbnail',
      'loyalty_discount_eligible',
      'immediate_payment',
      'cart_eligible',
      'shipping_guaranteed',
    ],
    order_backend: 2,
    use_thumbnail_id: true,
  },
];

export const details = {
  id: 'MLB1786478708',
  site_id: 'MLB',
  title: 'Computador Cpu Intel I3 4gb Ssd 120gb Hdmi Pronta Entrega',
  subtitle: null,
  seller_id: 298832663,
  category_id: 'MLB1649',
  official_store_id: null,
  price: 1200,
  base_price: 1200,
  original_price: null,
  currency_id: 'BRL',
  initial_quantity: 308,
  available_quantity: 1,
  sold_quantity: 250,
  sale_terms: [
    {
      id: 'WARRANTY_TIME',
      name: 'Tempo de garantia',
      value_id: null,
      value_name: '6 meses',
      value_struct: {
        number: 6,
        unit: 'meses',
      },
      values: [
        {
          id: null,
          name: '6 meses',
          struct: {
            number: 6,
            unit: 'meses',
          },
        },
      ],
    },
    {
      id: 'WARRANTY_TYPE',
      name: 'Tipo de garantia',
      value_id: '2230280',
      value_name: 'Garantia do vendedor',
      value_struct: null,
      values: [
        {
          id: '2230280',
          name: 'Garantia do vendedor',
          struct: null,
        },
      ],
    },
  ],
  buying_mode: 'buy_it_now',
  listing_type_id: 'gold_pro',
  start_time: '2021-02-03T16:52:22.000Z',
  stop_time: '2041-01-29T04:00:00.000Z',
  condition: 'new',
  permalink: 'https://produto.mercadolivre.com.br/MLB-1786478708-computador-cpu-intel-i3-4gb-ssd-120gb-hdmi-pronta-entrega-_JM',
  thumbnail_id: '783932-MLB43487722056_092020',
  thumbnail: 'http://http2.mlstatic.com/D_783932-MLB43487722056_092020-I.jpg',
  secure_thumbnail: 'https://http2.mlstatic.com/D_783932-MLB43487722056_092020-I.jpg',
  pictures: [
    {
      id: '783932-MLB43487722056_092020',
      url: 'http://http2.mlstatic.com/D_783932-MLB43487722056_092020-O.jpg',
      secure_url: 'https://http2.mlstatic.com/D_783932-MLB43487722056_092020-O.jpg',
      size: '345x500',
      max_size: '414x600',
      quality: '',
    },
    {
      id: '769277-MLB43487697540_092020',
      url: 'http://http2.mlstatic.com/D_769277-MLB43487697540_092020-O.jpg',
      secure_url: 'https://http2.mlstatic.com/D_769277-MLB43487697540_092020-O.jpg',
      size: '461x500',
      max_size: '642x696',
      quality: '',
    },
  ],
  video_id: null,
  descriptions: [
    {
      id: 'MLB1786478708-3213446082',
    },
  ],
  accepts_mercadopago: true,
  non_mercado_pago_payment_methods: [
  ],
  shipping: {
    mode: 'me2',
    free_methods: [
      {
        id: 100009,
        rule: {
          default: true,
          free_mode: 'country',
          free_shipping_flag: true,
          value: null,
        },
      },
    ],
    tags: [
      'self_service_in',
      'mandatory_free_shipping',
    ],
    dimensions: null,
    local_pick_up: false,
    free_shipping: true,
    logistic_type: 'cross_docking',
    store_pick_up: false,
  },
  international_delivery_mode: 'none',
  seller_address: {
    city: {
      id: 'BR-SP-44',
      name: 'São Paulo',
    },
    state: {
      id: 'BR-SP',
      name: 'São Paulo',
    },
    country: {
      id: 'BR',
      name: 'Brasil',
    },
    search_location: {
      neighborhood: {
        id: 'TUxCQlZJTHp5aDRu',
        name: 'Vila Água Funda',
      },
      city: {
        id: 'TUxCQ1NQLTkxMjE',
        name: 'São Paulo Zona Sul',
      },
      state: {
        id: 'TUxCUFNBT085N2E4',
        name: 'São Paulo',
      },
    },
    id: 618250284,
  },
  seller_contact: null,
  location: {
  },
  coverage_areas: [
  ],
  attributes: [
    {
      id: 'BRAND',
      name: 'Marca',
      value_id: null,
      value_name: 'GAME INFO',
      value_struct: null,
      values: [
        {
          id: null,
          name: 'GAME INFO',
          struct: null,
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Outros',
    },
    {
      id: 'DISPLAY_SIZE',
      name: 'Tamanho da tela',
      value_id: '-1',
      value_name: null,
      value_struct: null,
      values: [
        {
          id: '-1',
          name: null,
          struct: null,
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Outros',
    },
    {
      id: 'GTIN',
      name: 'Código universal de produto',
      value_id: null,
      value_name: '3000023615004',
      value_struct: null,
      values: [
        {
          id: null,
          name: '3000023615004',
          struct: null,
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Outros',
    },
    {
      id: 'HDD_SIZE',
      name: 'Disco rígido',
      value_id: '2932110',
      value_name: '120 GB',
      value_struct: {
        number: 120,
        unit: 'GB',
      },
      values: [
        {
          id: '2932110',
          name: '120 GB',
          struct: {
            number: 120,
            unit: 'GB',
          },
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Outros',
    },
    {
      id: 'ITEM_CONDITION',
      name: 'Condição do item',
      value_id: '2230284',
      value_name: 'Novo',
      value_struct: null,
      values: [
        {
          id: '2230284',
          name: 'Novo',
          struct: null,
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Outros',
    },
    {
      id: 'MODEL',
      name: 'Modelo',
      value_id: null,
      value_name: 'Office',
      value_struct: null,
      values: [
        {
          id: null,
          name: 'Office',
          struct: null,
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Outros',
    },
    {
      id: 'OPERATIVE_SYSTEM',
      name: 'Sistema operativo',
      value_id: '345583',
      value_name: 'Windows 10',
      value_struct: null,
      values: [
        {
          id: '345583',
          name: 'Windows 10',
          struct: null,
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Outros',
    },
    {
      id: 'PROCESSOR_TYPE',
      name: 'Processador',
      value_id: '345573',
      value_name: 'Intel Core i3',
      value_struct: null,
      values: [
        {
          id: '345573',
          name: 'Intel Core i3',
          struct: null,
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Outros',
    },
    {
      id: 'RAM_SIZE',
      name: 'RAM',
      value_id: null,
      value_name: '4 GB',
      value_struct: {
        number: 4,
        unit: 'GB',
      },
      values: [
        {
          id: null,
          name: '4 GB',
          struct: {
            number: 4,
            unit: 'GB',
          },
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Outros',
    },
  ],
  warnings: [
  ],
  listing_source: '',
  variations: [
  ],
  status: 'active',
  sub_status: [
  ],
  tags: [
    'good_quality_picture',
    'good_quality_thumbnail',
    'loyalty_discount_eligible',
    'immediate_payment',
    'cart_eligible',
  ],
  warranty: 'Garantia do vendedor: 6 meses',
  catalog_product_id: null,
  domain_id: 'MLB-DESKTOP_COMPUTERS',
  parent_item_id: null,
  differential_pricing: null,
  deal_ids: [
  ],
  automatic_relist: false,
  date_created: '2021-02-03T16:52:22.000Z',
  last_updated: '2021-05-07T01:32:36.000Z',
  health: 1,
  catalog_listing: false,
  channels: [
    'marketplace',
    'mshops',
  ],
};
